name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: coucou
        run: echo "coucou"
      - name: bye
        run: echo "au reveoir"
  
